# Generated by Django 5.0.6 on 2026-05-28 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255)),
                ('plant_code', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedEmissionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghg_scope', models.CharField(choices=[('Scope 1', 'Scope 1 - Direct Emissions'), ('Scope 2', 'Scope 2 - Indirect Emissions (Electricity)'), ('Scope 3', 'Scope 3 - Indirect Travel & Hotel')], max_length=20)),
                ('activity_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit', models.CharField(max_length=50)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged')], default='PENDING_REVIEW', max_length=20)),
                ('validation_issues', models.JSONField(blank=True, default=list)),
                ('is_locked', models.BooleanField(default=False)),
                ('original_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('original_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('original_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('activity_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='ingestion.facilityprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_activities', to='ingestion.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('field_modified', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.normalizedemissionactivity')),
            ],
        ),
        migrations.AddField(
            model_name='facilityprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='ingestion.organization'),
        ),
        migrations.CreateModel(
            name='StagingRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('raw_data', models.JSONField()),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_rows', to='ingestion.organization')),
            ],
        ),
        migrations.AddField(
            model_name='normalizedemissionactivity',
            name='staging_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_activities', to='ingestion.stagingrow'),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP Fuel & Procurement'), ('utility', 'Utility Electricity Data'), ('travel', 'Corporate Travel')], max_length=50)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='ingestion.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stagingrow',
            name='uploaded_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ingestion.uploadedfile'),
        ),
        migrations.AlterUniqueTogether(
            name='facilityprofile',
            unique_together={('organization', 'plant_code')},
        ),
    ]
